#!/usr/bin/env python3
"""
Notebook LM Report Generator
Automates report creation using Notebook LM Enterprise API
"""

import os
import sys
import json
import argparse
from pathlib import Path
from typing import List, Dict, Optional
import requests
from datetime import datetime


class NotebookLMReporter:
    """Handles interaction with Notebook LM API and report generation"""

    def __init__(
        self,
        project_id: str,
        location: str = "us-central1",
        credentials_path: Optional[str] = None
    ):
        self.project_id = project_id
        self.location = location
        self.credentials_path = credentials_path or os.getenv("GOOGLE_APPLICATION_CREDENTIALS")
        self.base_url = f"https://{location}-discoveryengine.googleapis.com/v1alpha"
        self.access_token = None

    def authenticate(self) -> str:
        """Get access token for API authentication"""
        try:
            # Using gcloud CLI for authentication
            import subprocess
            result = subprocess.run(
                ["gcloud", "auth", "print-access-token"],
                capture_output=True,
                text=True,
                check=True
            )
            self.access_token = result.stdout.strip()
            return self.access_token
        except Exception as e:
            print(f"Authentication failed: {e}", file=sys.stderr)
            print("Please ensure you're logged in with: gcloud auth login", file=sys.stderr)
            sys.exit(1)

    def create_notebook(self, notebook_name: str) -> Dict:
        """Create a new Notebook LM notebook"""
        if not self.access_token:
            self.authenticate()

        url = f"{self.base_url}/projects/{self.project_id}/locations/{self.location}/notebooks"
        headers = {
            "Authorization": f"Bearer {self.access_token}",
            "Content-Type": "application/json"
        }

        payload = {
            "displayName": notebook_name,
            "createTime": datetime.utcnow().isoformat() + "Z"
        }

        try:
            response = requests.post(url, headers=headers, json=payload)
            response.raise_for_status()
            return response.json()
        except requests.exceptions.RequestException as e:
            print(f"Failed to create notebook: {e}", file=sys.stderr)
            if hasattr(e, 'response') and e.response is not None:
                print(f"Response: {e.response.text}", file=sys.stderr)
            sys.exit(1)

    def add_sources_to_notebook(
        self,
        notebook_id: str,
        source_files: List[Path]
    ) -> List[Dict]:
        """Add source documents to the notebook"""
        sources_added = []

        for source_file in source_files:
            if source_file.suffix.lower() in ['.txt', '.md', '.pdf', '.docx']:
                print(f"Adding source: {source_file.name}")
                # In a real implementation, you would upload the file
                # For now, we'll simulate this
                sources_added.append({
                    "name": source_file.name,
                    "path": str(source_file),
                    "type": source_file.suffix[1:],
                    "size": source_file.stat().st_size
                })

        return sources_added

    def generate_report(
        self,
        notebook_id: str,
        output_format: str = "markdown"
    ) -> str:
        """Generate a report from the notebook"""
        # This would use the Notebook LM API to generate insights
        # For now, we'll create a structured report template

        report = f"""# Notebook LM Generated Report

**Generated**: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
**Notebook ID**: {notebook_id}

## Summary

This report was automatically generated using Notebook LM integration.

## Sources Analyzed

[Sources will be listed here]

## Key Insights

[AI-generated insights from Notebook LM will appear here]

## Citations

[Relevant citations with source references]

---
*Generated by Claude Code + Notebook LM*
"""
        return report

    def collect_source_files(self, source_dir: Path) -> List[Path]:
        """Collect all supported source files from directory"""
        supported_extensions = {'.txt', '.md', '.pdf', '.docx', '.doc'}
        source_files = []

        if not source_dir.exists():
            print(f"Source directory not found: {source_dir}", file=sys.stderr)
            return []

        for file_path in source_dir.rglob('*'):
            if file_path.is_file() and file_path.suffix.lower() in supported_extensions:
                source_files.append(file_path)

        return source_files


def main():
    parser = argparse.ArgumentParser(
        description="Generate reports using Notebook LM"
    )
    parser.add_argument(
        '--source-dir',
        type=Path,
        default=Path('./sources'),
        help='Directory containing source documents'
    )
    parser.add_argument(
        '--output-dir',
        type=Path,
        default=Path('./reports'),
        help='Directory for generated reports'
    )
    parser.add_argument(
        '--format',
        choices=['markdown', 'json', 'html'],
        default='markdown',
        help='Output format for the report'
    )
    parser.add_argument(
        '--notebook-name',
        default=f'Report_{datetime.now().strftime("%Y%m%d_%H%M%S")}',
        help='Name for the Notebook LM notebook'
    )

    args = parser.parse_args()

    # Validate environment variables
    project_id = os.getenv('NOTEBOOKLM_PROJECT_ID')
    location = os.getenv('NOTEBOOKLM_LOCATION', 'us-central1')

    if not project_id:
        print("Error: NOTEBOOKLM_PROJECT_ID environment variable not set", file=sys.stderr)
        print("For Notebook LM Enterprise, set your Google Cloud project ID", file=sys.stderr)
        sys.exit(1)

    # Initialize reporter
    reporter = NotebookLMReporter(project_id, location)

    print(f"📚 Notebook LM Report Generator")
    print(f"================================")
    print(f"Source directory: {args.source_dir}")
    print(f"Output directory: {args.output_dir}")
    print(f"Format: {args.format}")
    print(f"Notebook name: {args.notebook_name}")
    print()

    # Collect source files
    print("🔍 Collecting source files...")
    source_files = reporter.collect_source_files(args.source_dir)
    print(f"Found {len(source_files)} source file(s)")

    if not source_files:
        print("⚠️  No source files found. Exiting.")
        sys.exit(0)

    # Create notebook
    print(f"\n📝 Creating Notebook LM notebook: {args.notebook_name}...")
    try:
        notebook = reporter.create_notebook(args.notebook_name)
        notebook_id = notebook.get('name', 'unknown')
        print(f"✅ Notebook created: {notebook_id}")
    except Exception as e:
        print(f"⚠️  Using simulated notebook for demonstration")
        notebook_id = f"notebooks/{args.notebook_name}"

    # Add sources
    print(f"\n📤 Adding sources to notebook...")
    sources = reporter.add_sources_to_notebook(notebook_id, source_files)
    print(f"✅ Added {len(sources)} source(s)")

    # Generate report
    print(f"\n🤖 Generating report...")
    report_content = reporter.generate_report(notebook_id, args.format)

    # Save report
    args.output_dir.mkdir(parents=True, exist_ok=True)
    output_file = args.output_dir / f"report_{datetime.now().strftime('%Y%m%d_%H%M%S')}.{args.format}"
    output_file.write_text(report_content, encoding='utf-8')

    print(f"✅ Report generated: {output_file}")
    print(f"\n🎉 Done!")

    # Output summary as JSON for programmatic access
    summary = {
        "notebook_id": notebook_id,
        "sources_count": len(sources),
        "output_file": str(output_file),
        "format": args.format,
        "timestamp": datetime.now().isoformat()
    }

    summary_file = args.output_dir / "latest_report_summary.json"
    summary_file.write_text(json.dumps(summary, indent=2), encoding='utf-8')

    return 0


if __name__ == "__main__":
    sys.exit(main())
