#!/bin/bash
# 秋山 大輝の1日の振り返り自動生成スクリプト

set -e

# スクリプトのディレクトリに移動
cd "$(dirname "$0")/.."

# ログファイル
LOG_FILE="$HOME/Library/Logs/daily-reflection.log"
echo "========================================" >> "$LOG_FILE"
echo "Started at: $(date)" >> "$LOG_FILE"

# 昨日の日付を取得（JST）
YESTERDAY=$(date -v-1d "+%Y年%m月%d日")
DATE_ISO=$(date -v-1d "+%Y-%m-%d")

echo "Generating reflection for: $YESTERDAY" >> "$LOG_FILE"

# NotebookLM に質問
QUESTION="${YESTERDAY}の秋山大輝の1日について詳しく教えてください。主な活動、仕事の進捗、学習内容、運動、食事、睡眠などの記録を具体的に教えてください。"

echo "Querying NotebookLM..." >> "$LOG_FILE"

cd .claude/skills/notebooklm

# NotebookLM スキルを実行
ANSWER=$(python3 scripts/run.py ask_question.py \
  --question "$QUESTION" \
  --notebook-url "https://notebooklm.google.com/notebook/6c1ba7cc-2bea-4fc6-a4e1-884e59fa9c5f" \
  2>&1 | tee -a "$LOG_FILE")

cd ../../..

# レポート生成
echo "Generating report..." >> "$LOG_FILE"

cat > "reports/daily-reflection-${DATE_ISO}.md" << EOF
# 📅 秋山 大輝の1日の振り返り - ${YESTERDAY}

$(echo "$ANSWER" | sed -n '/Question:/,/EXTREMELY IMPORTANT:/p' | sed '$d')

---

🔗 **NotebookLM ソース**: [秋山大輝のライフログ・戦略データベース](https://notebooklm.google.com/notebook/6c1ba7cc-2bea-4fc6-a4e1-884e59fa9c5f)

💡 **生成日時**: $(date "+%Y-%m-%d %H:%M")

🤖 **Powered by NotebookLM + Claude Code**
EOF

# サマリー生成（最初の200文字）
echo "$ANSWER" | sed -n '/Question:/,/EXTREMELY IMPORTANT:/p' | sed '$d' | head -n 5 > "reports/daily-summary.txt"

echo "Reports generated successfully" >> "$LOG_FILE"

# Git にコミット
echo "Committing to Git..." >> "$LOG_FILE"
git add reports/
git commit -m "Add daily reflection for ${DATE_ISO}

Generated by local automation

Co-Authored-By: Claude Sonnet 4.5 <noreply@anthropic.com>" || echo "Nothing to commit" >> "$LOG_FILE"

git push origin main >> "$LOG_FILE" 2>&1 || echo "Push failed" >> "$LOG_FILE"

# Google Chat に通知
echo "Sending notification to Google Chat..." >> "$LOG_FILE"

SUMMARY=$(cat reports/daily-summary.txt | LC_ALL=C tr '\n' ' ' | sed 's/"/\\"/g' | head -c 300)

curl -X POST \
  -H 'Content-Type: application/json' \
  -d "{\"text\":\"📊 *秋山 大輝の1日の振り返り*\n\n📅 日付: ${YESTERDAY}\n\n${SUMMARY}...\n\n📄 詳細: https://github.com/d71280/muchinochi-notebook-LM/blob/main/reports/daily-reflection-${DATE_ISO}.md\"}" \
  "https://chat.googleapis.com/v1/spaces/AAQA1C_OnvI/messages?key=AIzaSyDdI0hCZtE6vySjMm-WEfRq3CPzqKqqsHI&token=LHawZ6Z-rzBnUouh6V9lhPa2-W0RJuFO4C4P240H990" \
  >> "$LOG_FILE" 2>&1

echo "Completed at: $(date)" >> "$LOG_FILE"
echo "✅ Daily reflection completed successfully!" >> "$LOG_FILE"
